version: "3.9"

services:

    prepare:
        image: alpine:3.18.3
        volumes:
            - .:/experiment:rw
            - ./scripts:/scripts:rw
        entrypoint: /bin/sh -c
        command: scripts/create-folders.sh

    learning-FBFL-MNIST:
        depends_on:
            prepare:
                condition: service_completed_successfully
        image: davidedomini99/experiment-fbfl-mnist
        volumes:
            - ./results:/experiment/results:rw

    learning-FBFL-Fashion:
        depends_on:
            prepare:
                condition: service_completed_successfully
        image: davidedomini99/experiment-fbfl-fashion
        volumes:
            - ./results:/experiment/results:rw

    learning-FL:
        depends_on:
            prepare:
                condition: service_completed_successfully
        image: davidedomini99/experiment-cfl-mnist
        volumes:
            - ./data:/experiment/data:rw

    clean-results:
        depends_on:
            prepare:
                condition: service_completed_successfully
            learning-FBFL-MNIST:
                condition: service_completed_successfully
            learning-FBFL-Fashion:
                condition: service_completed_successfully
        image: danysk/kotlin:1.9.22-jdk18
        volumes:
            - .:/experiment:rw
            - ./scripts:/scripts:rw
            - ./data:/data
            - ./results:/results
        command: scripts/clean-results.kts

    charts:
        depends_on:
            clean-results:
                condition: service_completed_successfully
            learning-FL:
                condition: service_completed_successfully
        image: davidedomini/plotter
        build:
            dockerfile: ./docker/charts/Dockerfile
            context: .
        volumes:
            - ./data:/experiment/data:rw
            - ./charts:/experiment/charts:rw